import type { Metadata } from "next";
import { Geist, Geist_Mono, Mona_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const monaSans = Mona_Sans({
  subsets: ['latin'],
  display: 'swap', // 'swap' ensures the fallback font is used until Mona Sans loads
  variable: '--font-mona-sans', // Optional: Use a CSS variable for easier styling
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monaSans.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
